#version: '3.8'
name: expense
networks:
  default:
    name: expense
volumes:
  mysql:
    #external: true # if true, you need to create manually
       # docker volume create myqsl
services:
  mysql:
    #image: mysql:v1.0
    image: mysql:v1.0
    container_name: mysql # --name mysql
    environment:  # we give env in run time to avoid to expose pass
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume # -v volume-name:/path/in/container
  backend:
    #image: backend:v1.0
    image: backend:v1.0
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"   # to sleep and connect to mysql 
    depends_on: 
    - mysql
  frontend:
    #image: frontend:v1.0
    image: frontend:v1.0
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"